name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    
# Add these if you plan to connect to Django later:ap
  http: ^1.1.0
  provider: ^6.0.0

  dio: ^5.4.3
  flutter_secure_storage: ^9.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Launcher icon generator
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

# Configuration for flutter_launcher_icons. After adding your source
# icon at `assets/icon/app_icon.png`, run:
#   flutter pub get
#   flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
